from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True
    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='코드')),
                ('name', models.CharField(max_length=50, verbose_name='브랜드명')),
                ('name_kr', models.CharField(max_length=50, verbose_name='브랜드명(한글)')),
            ],
            options={'verbose_name': '브랜드', 'verbose_name_plural': '브랜드'},
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='연도')),
                ('month', models.IntegerField(verbose_name='월')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='환율 (KRW/USD)')),
            ],
            options={'verbose_name': '환율', 'verbose_name_plural': '환율', 'ordering': ['year', 'month'], 'unique_together': {('year', 'month')}},
        ),
        migrations.CreateModel(
            name='DailySalesTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('year', models.IntegerField(verbose_name='연도')),
                ('month', models.IntegerField(verbose_name='월')),
                ('gmv', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='GMV')),
                ('gsv', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='GSV')),
                ('cogs', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='매출원가')),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='비용 합계')),
                ('performance_ad', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='퍼포먼스 광고비')),
                ('influencer_ad', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='인플루언서 광고비')),
                ('sales_commission', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='판매수수료')),
                ('shipping', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='운반비')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='세금')),
                ('operating_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='영업이익')),
                ('operating_margin', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True, verbose_name='영업이익률')),
            ],
            options={'verbose_name': '일별 전체 손익', 'verbose_name_plural': '일별 전체 손익', 'ordering': ['date'], 'unique_together': {('date',)}},
        ),
        migrations.CreateModel(
            name='DailySalesB2B',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('year', models.IntegerField(verbose_name='연도')),
                ('month', models.IntegerField(verbose_name='월')),
                ('sales_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='B2B 합계')),
                ('sales_us', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='미국')),
                ('cogs', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='매출원가')),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='비용 합계')),
                ('shipping', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='운반비')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='세금')),
                ('operating_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='영업이익')),
            ],
            options={'verbose_name': '일별 B2B 매출', 'verbose_name_plural': '일별 B2B 매출', 'ordering': ['date'], 'unique_together': {('date',)}},
        ),
        migrations.CreateModel(
            name='DailySalesB2C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('year', models.IntegerField(verbose_name='연도')),
                ('month', models.IntegerField(verbose_name='월')),
                ('b2c_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='B2C 합계')),
                ('shopify', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='쇼피파이')),
                ('amazon', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='아마존')),
                ('tiktok', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='틱톡샵')),
                ('refund_shopify', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='환불_쇼피파이')),
                ('refund_amazon', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='환불_아마존')),
                ('refund_tiktok', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='환불_틱톡샵')),
                ('refund_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='환불 합계')),
                ('gsv', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='GSV')),
                ('cogs', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='매출원가')),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='비용 합계')),
                ('performance_ad', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='퍼포먼스 광고비')),
                ('influencer_ad', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='인플루언서 광고비')),
                ('sales_commission', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='판매수수료')),
                ('shipping', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='운반비')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='세금')),
                ('operating_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='영업이익')),
                ('operating_margin', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True, verbose_name='영업이익률')),
            ],
            options={'verbose_name': '일별 B2C 매출', 'verbose_name_plural': '일별 B2C 매출', 'ordering': ['date'], 'unique_together': {('date',)}},
        ),
        migrations.CreateModel(
            name='BrandDailySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('year', models.IntegerField(verbose_name='연도')),
                ('month', models.IntegerField(verbose_name='월')),
                ('b2c_shopify', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='B2C 쇼피파이')),
                ('b2c_amazon', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='B2C 아마존')),
                ('b2c_tiktok', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='B2C 틱톡샵')),
                ('b2c_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='B2C 합계')),
                ('refund_shopify', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='환불 쇼피파이')),
                ('refund_amazon', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='환불 아마존')),
                ('refund_tiktok', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='환불 틱톡샵')),
                ('refund_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='환불 합계')),
                ('gsv', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='GSV')),
                ('b2b_us', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='B2B 미국')),
                ('b2b_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='B2B 합계')),
                ('total_gsv', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='전체 GSV')),
                ('ad_shopify', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='쇼피파이 광고비')),
                ('ad_amazon', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='아마존 광고비')),
                ('ad_tiktok', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='틱톡샵 광고비')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.brand', verbose_name='브랜드')),
            ],
            options={'verbose_name': '브랜드별 일별 매출', 'verbose_name_plural': '브랜드별 일별 매출', 'ordering': ['date', 'brand'], 'unique_together': {('date', 'brand')}},
        ),
        migrations.CreateModel(
            name='ShopifyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20, verbose_name='브랜드')),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='최종 매출')),
                ('order_date', models.DateField(null=True, verbose_name='날짜')),
                ('order_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='주문번호')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='이메일')),
                ('financial_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='결제상태')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='소계')),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='배송비')),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='세금')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='합계')),
                ('discount_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='할인코드')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='할인액')),
                ('lineitem_quantity', models.IntegerField(null=True, verbose_name='수량')),
                ('lineitem_name', models.TextField(blank=True, null=True, verbose_name='상품명')),
                ('lineitem_price', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='상품가격')),
                ('lineitem_sku', models.CharField(blank=True, max_length=50, null=True, verbose_name='SKU')),
                ('shipping_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='배송도시')),
                ('shipping_province', models.CharField(blank=True, max_length=100, null=True, verbose_name='배송주')),
                ('shipping_country', models.CharField(blank=True, max_length=10, null=True, verbose_name='배송국가')),
                ('shipping_zip', models.CharField(blank=True, max_length=20, null=True, verbose_name='우편번호')),
            ],
            options={'verbose_name': '쇼피파이 주문', 'verbose_name_plural': '쇼피파이 주문', 'ordering': ['-order_date']},
        ),
        migrations.CreateModel(
            name='TiktokOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20, verbose_name='브랜드')),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='최종 매출')),
                ('order_date', models.DateField(null=True, verbose_name='구매날짜')),
                ('cancel_date', models.DateField(blank=True, null=True, verbose_name='취소날짜')),
                ('order_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='주문ID')),
                ('order_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='주문상태')),
                ('seller_sku', models.CharField(blank=True, max_length=50, null=True, verbose_name='판매자SKU')),
                ('product_name', models.TextField(blank=True, null=True, verbose_name='상품명')),
                ('quantity', models.IntegerField(null=True, verbose_name='수량')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='단가')),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='주문금액')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='환불금액')),
                ('shipping_state', models.CharField(blank=True, max_length=100, null=True, verbose_name='배송주')),
                ('shipping_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='배송도시')),
                ('shipping_country', models.CharField(blank=True, max_length=50, null=True, verbose_name='배송국가')),
            ],
            options={'verbose_name': '틱톡샵 주문', 'verbose_name_plural': '틱톡샵 주문', 'ordering': ['-order_date']},
        ),
        migrations.CreateModel(
            name='TaxByState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(max_length=5, verbose_name='주 코드')),
                ('year', models.IntegerField(verbose_name='연도')),
                ('month', models.IntegerField(verbose_name='월')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='세금액($)')),
            ],
            options={'verbose_name': '주별 세금', 'verbose_name_plural': '주별 세금', 'ordering': ['year', 'month', 'state_code'], 'unique_together': {('state_code', 'year', 'month')}},
        ),
    ]
