# Generated by Django 4.2.28 on 2026-02-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Qoo10Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("us", "미국"),
                            ("cn", "중국"),
                            ("jp", "일본"),
                            ("global", "전체"),
                        ],
                        default="jp",
                        max_length=10,
                        verbose_name="지역",
                    ),
                ),
                ("brand", models.CharField(max_length=20, verbose_name="브랜드")),
                (
                    "final_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, null=True, verbose_name="최종 매출"
                    ),
                ),
                ("order_date", models.DateField(null=True, verbose_name="주문일자")),
                (
                    "order_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="주문번호"
                    ),
                ),
                (
                    "order_status",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="주문상태"
                    ),
                ),
                (
                    "product_name",
                    models.TextField(blank=True, null=True, verbose_name="상품명"),
                ),
                (
                    "seller_sku",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="판매자SKU"
                    ),
                ),
                ("quantity", models.IntegerField(null=True, verbose_name="수량")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, null=True, verbose_name="단가"
                    ),
                ),
                (
                    "order_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, null=True, verbose_name="주문금액"
                    ),
                ),
                (
                    "shipping_fee",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, null=True, verbose_name="배송비"
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, null=True, verbose_name="환불금액"
                    ),
                ),
            ],
            options={
                "verbose_name": "큐텐 주문",
                "verbose_name_plural": "큐텐 주문",
                "ordering": ["-order_date"],
            },
        ),
        migrations.CreateModel(
            name="ShopeeOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("us", "미국"),
                            ("cn", "중국"),
                            ("jp", "일본"),
                            ("global", "전체"),
                        ],
                        default="cn",
                        max_length=10,
                        verbose_name="지역",
                    ),
                ),
                ("brand", models.CharField(max_length=20, verbose_name="브랜드")),
                (
                    "final_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, null=True, verbose_name="최종 매출"
                    ),
                ),
                ("order_date", models.DateField(null=True, verbose_name="주문일자")),
                (
                    "order_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="주문번호"
                    ),
                ),
                (
                    "order_status",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="주문상태"
                    ),
                ),
                (
                    "product_name",
                    models.TextField(blank=True, null=True, verbose_name="상품명"),
                ),
                (
                    "seller_sku",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="판매자SKU"
                    ),
                ),
                ("quantity", models.IntegerField(null=True, verbose_name="수량")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, null=True, verbose_name="단가"
                    ),
                ),
                (
                    "order_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, null=True, verbose_name="주문금액"
                    ),
                ),
                (
                    "shipping_fee",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, null=True, verbose_name="배송비"
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, null=True, verbose_name="환불금액"
                    ),
                ),
                (
                    "buyer_country",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="구매자국가"
                    ),
                ),
            ],
            options={
                "verbose_name": "쇼피 주문",
                "verbose_name_plural": "쇼피 주문",
                "ordering": ["-order_date"],
            },
        ),
        migrations.AlterUniqueTogether(name="branddailysales", unique_together=set(),),
        migrations.AlterUniqueTogether(name="dailysalesb2b", unique_together=set(),),
        migrations.AlterUniqueTogether(name="dailysalesb2c", unique_together=set(),),
        migrations.AlterUniqueTogether(name="dailysalestotal", unique_together=set(),),
        migrations.AlterUniqueTogether(name="exchangerate", unique_together=set(),),
        migrations.AlterUniqueTogether(name="taxbystate", unique_together=set(),),
        migrations.AddField(
            model_name="brand",
            name="region",
            field=models.CharField(
                choices=[("us", "미국"), ("cn", "중국"), ("jp", "일본"), ("global", "전체")],
                default="us",
                max_length=10,
                verbose_name="지역",
            ),
        ),
        migrations.AddField(
            model_name="branddailysales",
            name="ad_qoo10",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="큐텐 광고비"
            ),
        ),
        migrations.AddField(
            model_name="branddailysales",
            name="ad_shopee",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="쇼피 광고비"
            ),
        ),
        migrations.AddField(
            model_name="branddailysales",
            name="b2c_qoo10",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="B2C 큐텐"
            ),
        ),
        migrations.AddField(
            model_name="branddailysales",
            name="b2c_shopee",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="B2C 쇼피"
            ),
        ),
        migrations.AddField(
            model_name="branddailysales",
            name="refund_qoo10",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="환불 큐텐"
            ),
        ),
        migrations.AddField(
            model_name="branddailysales",
            name="refund_shopee",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="환불 쇼피"
            ),
        ),
        migrations.AddField(
            model_name="branddailysales",
            name="region",
            field=models.CharField(
                choices=[("us", "미국"), ("cn", "중국"), ("jp", "일본"), ("global", "전체")],
                default="us",
                max_length=10,
                verbose_name="지역",
            ),
        ),
        migrations.AddField(
            model_name="dailysalesb2b",
            name="region",
            field=models.CharField(
                choices=[("us", "미국"), ("cn", "중국"), ("jp", "일본"), ("global", "전체")],
                default="us",
                max_length=10,
                verbose_name="지역",
            ),
        ),
        migrations.AddField(
            model_name="dailysalesb2c",
            name="qoo10",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="큐텐"
            ),
        ),
        migrations.AddField(
            model_name="dailysalesb2c",
            name="refund_qoo10",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="환불_큐텐"
            ),
        ),
        migrations.AddField(
            model_name="dailysalesb2c",
            name="refund_shopee",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="환불_쇼피"
            ),
        ),
        migrations.AddField(
            model_name="dailysalesb2c",
            name="region",
            field=models.CharField(
                choices=[("us", "미국"), ("cn", "중국"), ("jp", "일본"), ("global", "전체")],
                default="us",
                max_length=10,
                verbose_name="지역",
            ),
        ),
        migrations.AddField(
            model_name="dailysalesb2c",
            name="shopee",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="쇼피"
            ),
        ),
        migrations.AddField(
            model_name="dailysalestotal",
            name="region",
            field=models.CharField(
                choices=[("us", "미국"), ("cn", "중국"), ("jp", "일본"), ("global", "전체")],
                default="us",
                max_length=10,
                verbose_name="지역",
            ),
        ),
        migrations.AddField(
            model_name="exchangerate",
            name="region",
            field=models.CharField(
                choices=[("us", "미국"), ("cn", "중국"), ("jp", "일본"), ("global", "전체")],
                default="us",
                max_length=10,
                verbose_name="지역",
            ),
        ),
        migrations.AddField(
            model_name="shopifyorder",
            name="region",
            field=models.CharField(
                choices=[("us", "미국"), ("cn", "중국"), ("jp", "일본"), ("global", "전체")],
                default="us",
                max_length=10,
                verbose_name="지역",
            ),
        ),
        migrations.AddField(
            model_name="taxbystate",
            name="region",
            field=models.CharField(
                choices=[("us", "미국"), ("cn", "중국"), ("jp", "일본"), ("global", "전체")],
                default="us",
                max_length=10,
                verbose_name="지역",
            ),
        ),
        migrations.AddField(
            model_name="tiktokorder",
            name="region",
            field=models.CharField(
                choices=[("us", "미국"), ("cn", "중국"), ("jp", "일본"), ("global", "전체")],
                default="us",
                max_length=10,
                verbose_name="지역",
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="code",
            field=models.CharField(max_length=20, verbose_name="코드"),
        ),
        migrations.AlterUniqueTogether(
            name="brand", unique_together={("code", "region")},
        ),
        migrations.AlterUniqueTogether(
            name="branddailysales", unique_together={("date", "brand", "region")},
        ),
        migrations.AlterUniqueTogether(
            name="dailysalesb2b", unique_together={("date", "region")},
        ),
        migrations.AlterUniqueTogether(
            name="dailysalesb2c", unique_together={("date", "region")},
        ),
        migrations.AlterUniqueTogether(
            name="dailysalestotal", unique_together={("date", "region")},
        ),
        migrations.AlterUniqueTogether(
            name="exchangerate", unique_together={("year", "month", "region")},
        ),
        migrations.AlterUniqueTogether(
            name="taxbystate",
            unique_together={("state_code", "year", "month", "region")},
        ),
    ]
