# Generated by Django 4.2.28 on 2026-03-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_qoo10order_shopeeorder_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qoo10order",
            name="order_date",
            field=models.DateField(db_index=True, null=True, verbose_name="주문일자"),
        ),
        migrations.AlterField(
            model_name="qoo10order",
            name="region",
            field=models.CharField(
                choices=[("us", "미국"), ("cn", "중국"), ("jp", "일본"), ("global", "전체")],
                db_index=True,
                default="jp",
                max_length=10,
                verbose_name="지역",
            ),
        ),
        migrations.AlterField(
            model_name="shopeeorder",
            name="order_date",
            field=models.DateField(db_index=True, null=True, verbose_name="주문일자"),
        ),
        migrations.AlterField(
            model_name="shopeeorder",
            name="region",
            field=models.CharField(
                choices=[("us", "미국"), ("cn", "중국"), ("jp", "일본"), ("global", "전체")],
                db_index=True,
                default="cn",
                max_length=10,
                verbose_name="지역",
            ),
        ),
        migrations.AlterField(
            model_name="shopifyorder",
            name="order_date",
            field=models.DateField(db_index=True, null=True, verbose_name="날짜"),
        ),
        migrations.AlterField(
            model_name="shopifyorder",
            name="region",
            field=models.CharField(
                choices=[("us", "미국"), ("cn", "중국"), ("jp", "일본"), ("global", "전체")],
                db_index=True,
                default="us",
                max_length=10,
                verbose_name="지역",
            ),
        ),
        migrations.AlterField(
            model_name="tiktokorder",
            name="order_date",
            field=models.DateField(db_index=True, null=True, verbose_name="구매날짜"),
        ),
        migrations.AlterField(
            model_name="tiktokorder",
            name="region",
            field=models.CharField(
                choices=[("us", "미국"), ("cn", "중국"), ("jp", "일본"), ("global", "전체")],
                db_index=True,
                default="us",
                max_length=10,
                verbose_name="지역",
            ),
        ),
    ]
